@startuml
package de.thro.inf.prg3.a05 {

    +class PlantBed<T> {
        -plants: SimpleList<T>

        +add(plant: T)
        +size(): int
        +getPlantsByColor(color: PlantColor): SimpleList<T>
    }
}
@enduml
